version: "2"
services:
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./public/:/var/www/html/
        links:
            - db
        networks:
            - backend
    db:
        image: mysql
        ports: 
            - "3306:3306"
        environment:
           
           
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        command: mysqld --default-authentication-plugin=mysql_native_password
        networks:
            - backend
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:    
            MYSQL_ROOT_PASSWORD: root
        networks:
          - backend
volumes:
    persistent:
networks:
    backend: